---
title: "data_analysis"
output: html_notebook
---


#### import dataset and data cleaning
```{r}
library(dplyr)
library(haven)
dataset <- read_stata("data/Regression-and-Event-Study-Analyses.dta")

```


#### Descriptive statistics
```{r}
library(dplyr)
#demographics
#all
dataset %>%
  select(percent_female,percent_black,percent_nonwhite,percent_white,percent_other_nonwhite,percent_foreign,percent_age_less15,percent_age_15to44,percent_age_45plus) %>%
  summarise_all(list(mean = ~mean(.), sd = ~sd(.)))
#treatment group
dataset %>%
  filter(filter==1) %>%
  summarise(n=n())
dataset %>%
  filter(filter==1) %>%
  select(percent_female,percent_black,percent_nonwhite,percent_white,percent_other_nonwhite,percent_foreign,percent_age_less15,percent_age_15to44,percent_age_45plus) %>%
  summarise_all(list(mean = ~mean(.), sd = ~sd(.))) 
#control group
dataset %>%
  filter(filter<1) %>%
  summarise(n=n())
dataset %>%
  filter(filter<1) %>%
  select(percent_female,percent_black,percent_nonwhite,percent_white,percent_other_nonwhite,percent_foreign,percent_age_less15,percent_age_15to44,percent_age_45plus) %>%
  summarise_all(list(mean = ~mean(.), sd = ~sd(.)))

#Outcomes: filtration
#all
dataset %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))
#treatment
dataset %>%
   filter(filter==1) %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))
#control
dataset %>%
  filter(filter<1) %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))

test <- dataset %>%
  filter(filter<1 & filter>0)

#Outcomes: chlorination
#treatment
dataset %>%
   filter(chlorination==1) %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))
#control
dataset %>%
  filter(chlorination<1) %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))

#Outcomes: clean water project
#treatment
dataset %>%
   filter(water_project==1) %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))
#control
dataset %>%
  filter(water_project<1) %>%
  select(mortality_rate,mortality_under1_rate,typhoid_rate,diarrhea_rate) %>%
  summarise_all(list(mean = ~mean(.,na.rm = T), sd = ~sd(.,na.rm = T)))
```


### RD Regression

Model specification:

$ln(mortality_{ct}) = \beta_0 + \boldsymbol{Z}_{ct} \beta_1 + \boldsymbol{X}_{ct} \beta_2 + \nu_c + w_t + I(t > t^*) \beta_3 + \epsilon_{ct}$

$ln(mortality_{ct}) = \beta_0 + \boldsymbol{Z}_{ct} \beta_1 + \boldsymbol{X}_{ct} \beta_2 + \nu_c + w_t + \boldsymbol{Z}_{ct} \beta_3 I(t > t^*)  + \epsilon_{ct}$

```{r}
dat <- dataset %>% 
  select(year,
         city,
         city_id,
         percent_female,
         percent_nonwhite,
         percent_foreign,
         percent_age_less15,
         percent_age_15to44,
         percent_age_45plus, 
         mortality_rate,
         ln_mortality_rate,
         typhoid_rate,
         diarrhea_rate,
         filter, chlorination, water_project) %>% 
    mutate(filter = ifelse(filter == 1, 1, 0),
         chlorination = ifelse(chlorination == 1, 1, 0),
         water_project = ifelse(water_project == 1, 1, 0))

dat %>%
  group_by(year) %>%
  count(filter_bin)

```







